version: '3'
services:
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mongo
  mongo:
      image: mongo
      volumes:
        - mongodb_data:/data/db
volumes:
  mongodb_data:

    