version: '3'
services:
  web:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_DEBUG: "true"
    networks:
      - webnet
  redis:
    image: "redis:alpine"
    networks:
      - webnet

networks:
  webnet: